name: bike-sharing

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn = 1.5.2
  - jupyterlab
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - pmdarima
  - pytorch
  - pip
  - pip:
      - ucimlrepo
      - statsmodels
      - tqdm
      - ipywidgets
      - git+https://github.com/amazon-science/chronos-forecasting.git