name: bike-sharing

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - ucimlrepo
      - statsmodels
      - matplotlib